# -*- coding: utf-8 -*-
"""Individual Household Electric Power Consumption

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tGPYKGMUJcp24yI5GFPDc-5dylOLLc5u
"""

from google.colab import drive
drive.mount('/content/drive')

my_folder = "/content/drive/MyDrive/ Individual Household Electric Power Consumption"

import pandas as pd
import numpy as np

data = pd.read_csv('/content/drive/MyDrive/ Individual Household Electric Power Consumption/individual+household+electric+power+consumption (1).zip', sep=';',
                   parse_dates={'DateTime': ['Date', 'Time']},
                   infer_datetime_format=True, na_values='?',
                   low_memory=False)

data

data.set_index('DateTime', inplace=True)

data = data[['Global_active_power']]
data = data.astype('float')

data = data.resample('h').mean()

data = data.ffill()

import matplotlib.pyplot as plt

data['Global_active_power'].plot(figsize=(15,5), title='Hourly Global Active Power')
plt.ylabel('kilowatts')
plt.show()

df = data.reset_index()
df.columns = ['ds', 'y']

# Add Indian holidays
from prophet.make_holidays import make_holidays_df

# Create a holidays DataFrame for years in your data
holidays = make_holidays_df(year_list=[2007, 2008, 2009, 2010], country='IN')



from prophet import Prophet

model = Prophet(holidays=holidays)

model.fit(df)

future = model.make_future_dataframe(periods=168, freq='h')


forecast = model.predict(future)

# Plot the forecast
model.plot(forecast)

model.plot_components(forecast)

merged = df.merge(forecast[['ds', 'yhat']], on='ds', how='left')


merged.dropna(inplace=True)

from sklearn.metrics import mean_squared_error, mean_absolute_error
import numpy as np

rmse = np.sqrt(mean_squared_error(merged['y'], merged['yhat']))
mae = mean_absolute_error(merged['y'], merged['yhat'])

print("RMSE:", rmse)
print("MAE:", mae)